// Alerts.jsx — Alert monitoring and management page
// Alerts move through three statuses: ACTIVE → ACKNOWLEDGED → RESOLVED
// System alerts are auto-generated by the backend (low stock, maintenance due)
// Manual alerts can be created here for custom situations

import { useEffect, useState } from 'react';
import { alertApi } from '../../services/api';
import { Plus, X } from 'lucide-react';

// Badge colors mapped to each severity level
const SEVERITY_COLORS = {
  INFO:      'badge-blue',
  WARNING:   'badge-yellow',
  CRITICAL:  'badge-red',
  EMERGENCY: 'badge-red',
};

// Default empty form for creating a manual alert
const EMPTY_FORM = {
  title: '', message: '', severity: 'WARNING', type: 'CUSTOM'
};

export default function Alerts() {
  const [alerts, setAlerts]         = useState([]);   // list of alerts
  const [loading, setLoading]       = useState(true);
  const [showModal, setShowModal]   = useState(false);
  const [showResolveModal, setShowResolveModal] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState(null); // alert being resolved
  const [form, setForm]             = useState(EMPTY_FORM);
  const [resolveForm, setResolveForm] = useState({ resolvedBy: '', resolutionNotes: '' });
  const [filter, setFilter]         = useState('ACTIVE'); // default to active alerts

  // Load alerts filtered by status
  const load = () => {
    setLoading(true);
    alertApi.getAll(filter || undefined)
      .then(r => setAlerts(r.data.data || []))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [filter]);

  // Create a manual custom alert
  const handleCreate = async () => {
    await alertApi.create(form);
    setShowModal(false);
    load();
  };

  // Acknowledge — signals someone has seen the alert but not fixed it yet
  // Uses hardcoded 'Operator' as acknowledgedBy for simplicity
  const handleAcknowledge = async (id) => {
    await alertApi.acknowledge(id, 'Operator');
    load();
  };

  // Resolve — marks the alert as fully handled
  const handleResolve = async () => {
    await alertApi.resolve(selectedAlert.id, resolveForm);
    setShowResolveModal(false);
    load();
  };

  return (
    <div>
      {/* ── Page Header ───────────────────────────────────── */}
      <div className="page-header">
        <div>
          <div className="page-title">Alerts</div>
          <div className="page-subtitle">Monitor and respond to system alerts</div>
        </div>
        <button className="btn btn-primary" onClick={() => { setForm(EMPTY_FORM); setShowModal(true); }}>
          <Plus size={16} /> Create Alert
        </button>
      </div>

      {/* ── Status Filter ─────────────────────────────────── */}
      <div className="filters">
        <select value={filter} onChange={e => setFilter(e.target.value)}>
          <option value="ACTIVE">Active</option>
          <option value="ACKNOWLEDGED">Acknowledged</option>
          <option value="RESOLVED">Resolved</option>
          <option value="">All</option>
        </select>
      </div>

      {/* ── Alerts Table ──────────────────────────────────── */}
      {loading ? <div className="loading">Loading...</div> : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Type</th>
                <th>Severity</th>
                <th>Status</th>
                <th>Equipment</th>
                <th>Created</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={7} style={{ textAlign: 'center', color: 'var(--text-muted)', padding: 32 }}>
                    No alerts found
                  </td>
                </tr>
              ) : alerts.map(alert => (
                <tr key={alert.id}>
                  <td style={{ fontWeight: 600 }}>{alert.title}</td>
                  <td style={{ color: 'var(--text-muted)' }}>{alert.type}</td>
                  <td>
                    <span className={`badge ${SEVERITY_COLORS[alert.severity]}`}>
                      {alert.severity}
                    </span>
                  </td>
                  <td>
                    <span className="badge badge-gray">{alert.status}</span>
                  </td>
                  <td>{alert.equipment?.name || '—'}</td>
                  <td>
                    {alert.createdAt ? new Date(alert.createdAt).toLocaleString() : '—'}
                  </td>
                  <td style={{ display: 'flex', gap: 6 }}>
                    {/* Acknowledge button — only for ACTIVE alerts */}
                    {alert.status === 'ACTIVE' && (
                      <button
                        className="btn btn-secondary btn-sm"
                        onClick={() => handleAcknowledge(alert.id)}
                      >
                        Acknowledge
                      </button>
                    )}
                    {/* Resolve button — for ACTIVE or ACKNOWLEDGED alerts */}
                    {(alert.status === 'ACTIVE' || alert.status === 'ACKNOWLEDGED') && (
                      <button
                        className="btn btn-primary btn-sm"
                        onClick={() => {
                          setSelectedAlert(alert);
                          setResolveForm({ resolvedBy: '', resolutionNotes: '' });
                          setShowResolveModal(true);
                        }}
                      >
                        Resolve
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ── Create Alert Modal ────────────────────────────── */}
      {showModal && (
        <div className="modal-overlay">
          <div className="modal">
            <div className="modal-header">
              <div className="modal-title">Create Alert</div>
              <button className="modal-close" onClick={() => setShowModal(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="form-group">
              <label>Title *</label>
              <input
                value={form.title}
                onChange={e => setForm({ ...form, title: e.target.value })}
                placeholder="Equipment overheating"
              />
            </div>

            <div className="grid-2">
              <div className="form-group">
                <label>Severity</label>
                <select
                  value={form.severity}
                  onChange={e => setForm({ ...form, severity: e.target.value })}
                >
                  <option value="INFO">Info</option>
                  <option value="WARNING">Warning</option>
                  <option value="CRITICAL">Critical</option>
                  <option value="EMERGENCY">Emergency</option>
                </select>
              </div>
              <div className="form-group">
                <label>Type</label>
                <select
                  value={form.type}
                  onChange={e => setForm({ ...form, type: e.target.value })}
                >
                  <option value="CUSTOM">Custom</option>
                  <option value="EQUIPMENT_FAULT">Equipment Fault</option>
                  <option value="MAINTENANCE_DUE">Maintenance Due</option>
                  <option value="LOW_INVENTORY">Low Inventory</option>
                  <option value="SAFETY">Safety</option>
                </select>
              </div>
            </div>

            <div className="form-group">
              <label>Message</label>
              <textarea
                rows={3}
                value={form.message}
                onChange={e => setForm({ ...form, message: e.target.value })}
              />
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={handleCreate}>Create Alert</button>
            </div>
          </div>
        </div>
      )}

      {/* ── Resolve Alert Modal ───────────────────────────── */}
      {showResolveModal && (
        <div className="modal-overlay">
          <div className="modal">
            <div className="modal-header">
              <div className="modal-title">Resolve — {selectedAlert?.title}</div>
              <button className="modal-close" onClick={() => setShowResolveModal(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="form-group">
              <label>Resolved By</label>
              <input
                value={resolveForm.resolvedBy}
                onChange={e => setResolveForm({ ...resolveForm, resolvedBy: e.target.value })}
                placeholder="John Smith"
              />
            </div>
            <div className="form-group">
              <label>Resolution Notes</label>
              <textarea
                rows={3}
                value={resolveForm.resolutionNotes}
                onChange={e => setResolveForm({ ...resolveForm, resolutionNotes: e.target.value })}
                placeholder="Issue identified and fixed"
              />
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setShowResolveModal(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={handleResolve}>Resolve</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}