// WorkOrders.jsx — Work Order management page
// Tracks maintenance work orders through their full lifecycle:
// OPEN → IN_PROGRESS → COMPLETED (or CANCELLED)
// Work order numbers are auto-generated by the Spring Boot backend

import { useEffect, useState } from 'react';
import { workOrderApi, equipmentApi } from '../../services/api';
import { Plus, X } from 'lucide-react';

// Badge colors mapped to each work order status
const STATUS_COLORS = {
  OPEN:        'badge-blue',
  IN_PROGRESS: 'badge-yellow',
  ON_HOLD:     'badge-gray',
  COMPLETED:   'badge-green',
  CANCELLED:   'badge-gray',
};

// Badge colors mapped to each priority level
const PRIORITY_COLORS = {
  LOW:      'badge-gray',
  MEDIUM:   'badge-blue',
  HIGH:     'badge-yellow',
  CRITICAL: 'badge-red',
};

// Default empty form for creating a new work order
const EMPTY_FORM = {
  title: '', description: '', type: 'CORRECTIVE', priority: 'MEDIUM',
  assignedTechnician: '', scheduledDate: '', estimatedDurationMinutes: '',
  equipmentId: '',
};

export default function WorkOrders() {
  const [workOrders, setWorkOrders] = useState([]);  // all work orders
  const [equipment, setEquipment]   = useState([]);  // for equipment dropdown
  const [loading, setLoading]       = useState(true);
  const [showModal, setShowModal]   = useState(false);
  const [showCompleteModal, setShowCompleteModal] = useState(false);
  const [selectedWo, setSelectedWo] = useState(null); // WO being completed
  const [form, setForm]             = useState(EMPTY_FORM);
  const [completeForm, setCompleteForm] = useState({
    completionNotes: '', laborCost: '', partsCost: ''
  });
  const [filterStatus, setFilterStatus] = useState('');

  // Load work orders and equipment list together
  const load = () => {
    setLoading(true);
    Promise.all([
      workOrderApi.getAll(filterStatus ? { status: filterStatus } : {}),
      equipmentApi.getAll(),
    ]).then(([woRes, eqRes]) => {
      setWorkOrders(woRes.data.data || []);
      setEquipment(eqRes.data.data || []);
    }).finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, [filterStatus]);

  // Create a new work order
  // Equipment is sent as an object with just the id — Spring Boot resolves the rest
  const handleCreate = async () => {
    const payload = { ...form };
    if (form.equipmentId) payload.equipment = { id: parseInt(form.equipmentId) };
    await workOrderApi.create(payload);
    setShowModal(false);
    load();
  };

  // Move work order from OPEN to IN_PROGRESS and set startedAt timestamp
  const handleStart = async (id) => {
    await workOrderApi.start(id);
    load();
  };

  // Complete a work order — records cost and completion notes
  const handleComplete = async () => {
    await workOrderApi.complete(selectedWo.id, {
      completionNotes: completeForm.completionNotes,
      laborCost: completeForm.laborCost ? parseFloat(completeForm.laborCost) : null,
      partsCost: completeForm.partsCost ? parseFloat(completeForm.partsCost) : null,
    });
    setShowCompleteModal(false);
    load();
  };

  // Cancel a work order
  const handleCancel = async (id) => {
    await workOrderApi.cancel(id);
    load();
  };

  return (
    <div>
      {/* ── Page Header ───────────────────────────────────── */}
      <div className="page-header">
        <div>
          <div className="page-title">Work Orders</div>
          <div className="page-subtitle">Track and manage maintenance work orders</div>
        </div>
        <button className="btn btn-primary" onClick={() => { setForm(EMPTY_FORM); setShowModal(true); }}>
          <Plus size={16} /> New Work Order
        </button>
      </div>

      {/* ── Status Filter ─────────────────────────────────── */}
      <div className="filters">
        <select value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
          <option value="">All Statuses</option>
          <option value="OPEN">Open</option>
          <option value="IN_PROGRESS">In Progress</option>
          <option value="ON_HOLD">On Hold</option>
          <option value="COMPLETED">Completed</option>
          <option value="CANCELLED">Cancelled</option>
        </select>
      </div>

      {/* ── Work Orders Table ─────────────────────────────── */}
      {loading ? <div className="loading">Loading...</div> : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>WO Number</th>
                <th>Title</th>
                <th>Type</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Equipment</th>
                <th>Technician</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {workOrders.length === 0 ? (
                <tr>
                  <td colSpan={8} style={{ textAlign: 'center', color: 'var(--text-muted)', padding: 32 }}>
                    No work orders found
                  </td>
                </tr>
              ) : workOrders.map(wo => (
                <tr key={wo.id}>
                  {/* Monospace font makes the WO number easy to read */}
                  <td style={{ fontFamily: 'monospace', fontSize: 12 }}>{wo.workOrderNumber}</td>
                  <td style={{ fontWeight: 600 }}>{wo.title}</td>
                  <td>{wo.type}</td>
                  <td>
                    <span className={`badge ${PRIORITY_COLORS[wo.priority]}`}>
                      {wo.priority}
                    </span>
                  </td>
                  <td>
                    <span className={`badge ${STATUS_COLORS[wo.status]}`}>
                      {wo.status}
                    </span>
                  </td>
                  <td>{wo.equipment?.name || '—'}</td>
                  <td>{wo.assignedTechnician || '—'}</td>
                  <td style={{ display: 'flex', gap: 6 }}>
                    {/* Show Start button only when OPEN */}
                    {wo.status === 'OPEN' && (
                      <button className="btn btn-secondary btn-sm" onClick={() => handleStart(wo.id)}>
                        Start
                      </button>
                    )}
                    {/* Show Complete button only when IN_PROGRESS */}
                    {wo.status === 'IN_PROGRESS' && (
                      <button className="btn btn-primary btn-sm" onClick={() => {
                        setSelectedWo(wo);
                        setShowCompleteModal(true);
                      }}>
                        Complete
                      </button>
                    )}
                    {/* Show Cancel button when OPEN or IN_PROGRESS */}
                    {(wo.status === 'OPEN' || wo.status === 'IN_PROGRESS') && (
                      <button className="btn btn-danger btn-sm" onClick={() => handleCancel(wo.id)}>
                        Cancel
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ── Create Work Order Modal ───────────────────────── */}
      {showModal && (
        <div className="modal-overlay">
          <div className="modal">
            <div className="modal-header">
              <div className="modal-title">New Work Order</div>
              <button className="modal-close" onClick={() => setShowModal(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="form-group">
              <label>Title *</label>
              <input
                value={form.title}
                onChange={e => setForm({ ...form, title: e.target.value })}
                placeholder="Replace conveyor belt"
              />
            </div>

            <div className="grid-2">
              <div className="form-group">
                <label>Type</label>
                <select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}>
                  <option value="CORRECTIVE">Corrective</option>
                  <option value="PREVENTIVE">Preventive</option>
                  <option value="EMERGENCY">Emergency</option>
                  <option value="INSPECTION">Inspection</option>
                </select>
              </div>
              <div className="form-group">
                <label>Priority</label>
                <select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}>
                  <option value="LOW">Low</option>
                  <option value="MEDIUM">Medium</option>
                  <option value="HIGH">High</option>
                  <option value="CRITICAL">Critical</option>
                </select>
              </div>
              <div className="form-group">
                <label>Equipment</label>
                <select value={form.equipmentId} onChange={e => setForm({ ...form, equipmentId: e.target.value })}>
                  <option value="">None</option>
                  {equipment.map(eq => (
                    <option key={eq.id} value={eq.id}>{eq.name}</option>
                  ))}
                </select>
              </div>
              <div className="form-group">
                <label>Technician</label>
                <input
                  value={form.assignedTechnician}
                  onChange={e => setForm({ ...form, assignedTechnician: e.target.value })}
                  placeholder="John Smith"
                />
              </div>
              <div className="form-group">
                <label>Scheduled Date</label>
                <input
                  type="datetime-local"
                  value={form.scheduledDate}
                  onChange={e => setForm({ ...form, scheduledDate: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Est. Duration (mins)</label>
                <input
                  type="number"
                  value={form.estimatedDurationMinutes}
                  onChange={e => setForm({ ...form, estimatedDurationMinutes: e.target.value })}
                />
              </div>
            </div>

            <div className="form-group">
              <label>Description</label>
              <textarea
                rows={3}
                value={form.description}
                onChange={e => setForm({ ...form, description: e.target.value })}
              />
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={handleCreate}>Create Work Order</button>
            </div>
          </div>
        </div>
      )}

      {/* ── Complete Work Order Modal ─────────────────────── */}
      {/* Records labor cost, parts cost and completion notes */}
      {showCompleteModal && (
        <div className="modal-overlay">
          <div className="modal">
            <div className="modal-header">
              <div className="modal-title">Complete Work Order</div>
              <button className="modal-close" onClick={() => setShowCompleteModal(false)}>
                <X size={18} />
              </button>
            </div>

            <div className="form-group">
              <label>Completion Notes</label>
              <textarea
                rows={3}
                value={completeForm.completionNotes}
                onChange={e => setCompleteForm({ ...completeForm, completionNotes: e.target.value })}
              />
            </div>

            <div className="grid-2">
              <div className="form-group">
                <label>Labor Cost ($)</label>
                <input
                  type="number"
                  value={completeForm.laborCost}
                  onChange={e => setCompleteForm({ ...completeForm, laborCost: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label>Parts Cost ($)</label>
                <input
                  type="number"
                  value={completeForm.partsCost}
                  onChange={e => setCompleteForm({ ...completeForm, partsCost: e.target.value })}
                />
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setShowCompleteModal(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={handleComplete}>Mark Complete</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}